[project]
name = "modal-comfyui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.47.2",
    "modal>=1.1.4",
    "pillow>=11.0.0",
    "python-dotenv>=1.0.1",
]

[project.optional-dependencies]
ambient = ["ambient-comfyui==0.1.0"]
split-test = ["aiohttp>=3.12.15"]
ambient-test = ["ambient-comfyui==0.1.0", "aiohttp>=3.12.15"]

[tool.flake8]
max-line-length = 100

[tool.uv.sources]
ambient-comfyui = { git = "https://github.com/hndrr/ComfyUI-Ambient", rev = "c40aa0d4cbde7ab570a04afe91590f03ba62d56f" }
